/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.cloud.ai.dataagent.workflow.node;

import static com.alibaba.cloud.ai.dataagent.constant.Constant.PLAN_CURRENT_STEP;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.LIGHTWEIGHT_SQL_RESULT_MODE;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_EXECUTE_NODE_OUTPUT;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_GENERATE_COUNT;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_GENERATE_OUTPUT;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_REGENERATE_REASON;
import static com.alibaba.cloud.ai.dataagent.constant.Constant.SQL_RESULT_LIST_MEMORY;

import com.alibaba.cloud.ai.dataagent.bo.DbConfigBO;
import com.alibaba.cloud.ai.dataagent.bo.schema.DisplayStyleBO;
import com.alibaba.cloud.ai.dataagent.bo.schema.ResultBO;
import com.alibaba.cloud.ai.dataagent.bo.schema.ResultSetBO;
import com.alibaba.cloud.ai.dataagent.connector.DbQueryParameter;
import com.alibaba.cloud.ai.dataagent.connector.accessor.Accessor;
import com.alibaba.cloud.ai.dataagent.constant.Constant;
import com.alibaba.cloud.ai.dataagent.dto.datasource.SqlRetryDto;
import com.alibaba.cloud.ai.dataagent.dto.planner.ExecutionStep;
import com.alibaba.cloud.ai.dataagent.enums.TextType;
import com.alibaba.cloud.ai.dataagent.prompt.PromptHelper;
import com.alibaba.cloud.ai.dataagent.properties.DataAgentProperties;
import com.alibaba.cloud.ai.dataagent.service.llm.LlmService;
import com.alibaba.cloud.ai.dataagent.service.nl2sql.Nl2SqlService;
import com.alibaba.cloud.ai.dataagent.util.ChatResponseUtil;
import com.alibaba.cloud.ai.dataagent.util.DatabaseUtil;
import com.alibaba.cloud.ai.dataagent.util.FluxUtil;
import com.alibaba.cloud.ai.dataagent.util.JsonParseUtil;
import com.alibaba.cloud.ai.dataagent.util.JsonUtil;
import com.alibaba.cloud.ai.dataagent.util.MarkdownParserUtil;
import com.alibaba.cloud.ai.dataagent.util.PlanProcessUtil;
import com.alibaba.cloud.ai.dataagent.util.StateUtil;
import com.alibaba.cloud.ai.graph.GraphResponse;
import com.alibaba.cloud.ai.graph.OverAllState;
import com.alibaba.cloud.ai.graph.action.NodeAction;
import com.alibaba.cloud.ai.graph.streaming.StreamingOutput;
import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Flux;

/**
 * SQL execution node that executes SQL queries against the database.
 *
 * <p>
 * This node is responsible for: - Executing SQL queries generated by previous nodes -
 * Handling query results and errors - Providing streaming feedback to users during
 * execution - Managing step-by-step result accumulation
 *
 * @author zhangshenghang
 */
@Slf4j
@Component
@AllArgsConstructor
public class SqlExecuteNode implements NodeAction {

	private final DatabaseUtil databaseUtil;

	private final Nl2SqlService nl2SqlService;

	private final LlmService llmService;

	private final DataAgentProperties properties;

	private final JsonParseUtil jsonParseUtil;

	private static final int SAMPLE_DATA_NUMBER = 20;

	private static final String EMPTY_RESULT_MESSAGE = "SQL执行完成，但未查询到符合条件的数据。";

	private static final Pattern PRIMARY_TABLE_PATTERN = Pattern
		.compile("(?i)\\bFROM\\s+\\[?([A-Za-z0-9_\\u4e00-\\u9fa5]+)\\]?");

	@Override
	public Map<String, Object> apply(OverAllState state) throws Exception {

		Integer currentStep = PlanProcessUtil.getCurrentStepNumber(state);

		String sqlQuery = StateUtil.getStringValue(state, SQL_GENERATE_OUTPUT);
		sqlQuery = nl2SqlService.sqlTrim(sqlQuery);

		log.info("Executing SQL query: {}", sqlQuery);

		// Get the agent ID from the state
		String agentIdStr = StateUtil.getStringValue(state, Constant.AGENT_ID);
		if (StringUtils.isBlank(agentIdStr)) {
			throw new IllegalStateException("Agent ID cannot be empty.");
		}

		Long agentId = Long.valueOf(agentIdStr);

		// Dynamically get the data source configuration for an agent
		DbConfigBO dbConfig = databaseUtil.getAgentDbConfig(agentId);

		return executeSqlQuery(state, currentStep, sqlQuery, dbConfig, agentId);
	}

	/**
	 * Executes the SQL query against the database and handles the results.
	 *
	 * <p>
	 * This method follows the business-logic-first pattern: 1. Execute the actual SQL
	 * query immediately 2. Process and store the results 3. Create streaming output for
	 * user experience only
	 * @param state The overall state containing execution context
	 * @param currentStep The current step number in the execution plan
	 * @param sqlQuery The SQL query to execute
	 * @param dbConfig The database configuration to use for execution
	 * @param agentId The agent ID
	 * @return Map containing the generator for streaming output
	 */
	@SuppressWarnings("unchecked")
	private Map<String, Object> executeSqlQuery(OverAllState state, Integer currentStep, String sqlQuery,
			DbConfigBO dbConfig, Long agentId) {
		// Execute business logic first - actual SQL execution
		DbQueryParameter dbQueryParameter = new DbQueryParameter();
		dbQueryParameter.setSql(sqlQuery);
		dbQueryParameter.setSchema(dbConfig.getSchema());

		Accessor dbAccessor = databaseUtil.getAgentAccessor(agentId);
		final Map<String, Object> result = new HashMap<>();

		// 先返回流式数据，在执行数据库查询
		Flux<ChatResponse> displayFlux = Flux.create(emitter -> {
			emitter.next(ChatResponseUtil.createResponse("开始执行SQL..."));
			emitter.next(ChatResponseUtil.createResponse("执行SQL查询："));
			emitter.next(ChatResponseUtil.createPureResponse(TextType.SQL.getStartSign()));
			emitter.next(ChatResponseUtil.createResponse(sqlQuery));
			emitter.next(ChatResponseUtil.createPureResponse(TextType.SQL.getEndSign()));
			ResultBO resultBO = ResultBO.builder().build();

				try {
					// Execute SQL query and get results immediately
					ResultSetBO resultSetBO = dbAccessor.executeSqlAndReturnObject(dbConfig, dbQueryParameter);
					SqlRetryDto resultStatus = classifyQueryResult(state, resultSetBO);
					if (!SqlRetryDto.SqlRetryType.NONE.equals(resultStatus.type())) {
						result.put(SQL_REGENERATE_REASON, resultStatus);
						emitter.next(ChatResponseUtil.createResponse(resultStatus.reason()));
						return;
					}
					// 调用大模型获取图表配置信息并填充到ResultSetBO中
					DisplayStyleBO displayStyleBO = isLightweightSqlResultMode(state) ? null
							: enrichResultSetWithChartConfig(state, resultSetBO);
				resultBO.setResultSet(resultSetBO);
				resultBO.setDisplayStyle(displayStyleBO);

				String strResultSetJson = JsonUtil.getObjectMapper().writeValueAsString(resultSetBO);
				String strResultJson = JsonUtil.getObjectMapper().writeValueAsString(resultBO);

				// 数据执行成功
				emitter.next(ChatResponseUtil.createResponse("执行SQL完成"));
				emitter.next(ChatResponseUtil.createResponse("SQL查询结果："));
				emitter.next(ChatResponseUtil.createPureResponse(TextType.RESULT_SET.getStartSign()));
				emitter.next(ChatResponseUtil.createPureResponse(strResultJson));
				emitter.next(ChatResponseUtil.createPureResponse(TextType.RESULT_SET.getEndSign()));

				// Update step results with the query output
				Map<String, String> existingResults = StateUtil.getObjectValue(state, SQL_EXECUTE_NODE_OUTPUT,
						Map.class, new HashMap<>());
				Map<String, String> updatedResults = PlanProcessUtil.addStepResult(existingResults, currentStep,
						strResultSetJson);

				log.info("SQL execution successful, result count: {}",
						resultSetBO.getData() != null ? resultSetBO.getData().size() : 0);

				// 回写最终执行的sql，报告节点需要使用
				ExecutionStep.ToolParameters currentStepParams = PlanProcessUtil.getCurrentExecutionStep(state)
					.getToolParameters();
				currentStepParams.setSqlQuery(sqlQuery);

				// Prepare the final result object
				// Store List of SQL query results for use by code execution node
				// Reset sql generate count retry times when sql execute success
				result.putAll(Map.of(SQL_EXECUTE_NODE_OUTPUT, updatedResults, SQL_REGENERATE_REASON,
						SqlRetryDto.empty(), SQL_RESULT_LIST_MEMORY,
						buildSqlResultMemory(state, currentStep, sqlQuery, resultSetBO), PLAN_CURRENT_STEP,
						currentStep + 1, SQL_GENERATE_COUNT, 0));
				}
				catch (Exception e) {
					String errorMessage = e.getMessage();
					log.error("SQL execution failed - SQL as follows: \n {} \n ", sqlQuery, e);
					SqlRetryDto retryStatus = classifyExecutionException(errorMessage);
					result.put(SQL_REGENERATE_REASON, retryStatus);
					emitter.next(ChatResponseUtil.createResponse("SQL执行失败: " + retryStatus.reason()));
				}
			finally {
				emitter.complete();
			}
		});

		// Create generator using utility class, returning pre-computed business logic
		// result
		Flux<GraphResponse<StreamingOutput>> generator = FluxUtil.createStreamingGeneratorWithMessages(this.getClass(),
				state, v -> result, displayFlux);
		return Map.of(SQL_EXECUTE_NODE_OUTPUT, generator);
	}

	@SuppressWarnings("unchecked")
	private List<Map<String, Object>> buildSqlResultMemory(OverAllState state, Integer currentStep, String sqlQuery,
			ResultSetBO resultSetBO) {
		List<Map<String, Object>> existingMemory = StateUtil.hasValue(state, SQL_RESULT_LIST_MEMORY)
				? StateUtil.getListValue(state, SQL_RESULT_LIST_MEMORY) : new ArrayList<>();
		List<Map<String, Object>> mergedMemory = new ArrayList<>(existingMemory);

		Map<String, Object> currentStepResult = new HashMap<>();
		currentStepResult.put("step", "step_" + currentStep);
		currentStepResult.put("sql_query", sqlQuery);
		currentStepResult.put("table_name", extractPrimaryTableName(sqlQuery));
		currentStepResult.put("columns", resultSetBO.getColumn());
		currentStepResult.put("data", resultSetBO.getData());
		mergedMemory.add(currentStepResult);
		return mergedMemory;
	}

	private String extractPrimaryTableName(String sqlQuery) {
		if (StringUtils.isBlank(sqlQuery)) {
			return "";
		}
		Matcher matcher = PRIMARY_TABLE_PATTERN.matcher(sqlQuery);
		return matcher.find() ? matcher.group(1) : "";
	}

	private boolean isLightweightSqlResultMode(OverAllState state) {
		return StateUtil.getObjectValue(state, LIGHTWEIGHT_SQL_RESULT_MODE, Boolean.class, false);
	}

	/**
	 * 调用大模型获取图表配置信息并填充到ResultSetBO中
	 * @param state 整体状态
	 * @param resultSetBO SQL执行结果
	 */
	private DisplayStyleBO enrichResultSetWithChartConfig(OverAllState state, ResultSetBO resultSetBO) {
		// 创建ResultDisplayStyleBO对象
		DisplayStyleBO displayStyle = new DisplayStyleBO();
		if (!this.properties.isEnableSqlResultChart()) {
			log.debug("Sql result chart is disabled, set display style as table default");
			displayStyle.setType("table");
			return displayStyle;
		}

		try {
			// 获取用户查询
			String userQuery = StateUtil.getCanonicalQuery(state);

			// 将SQL结果转换为JSON字符串，限制数据量以避免提示词过长
			String sqlResultJson = JsonUtil.getObjectMapper()
				.writeValueAsString(resultSetBO.getData() != null
						? resultSetBO.getData().stream().limit(SAMPLE_DATA_NUMBER).toList() : null);

			// 构建用户提示词，包含SQL结果数据
			String userPrompt = String.format("""
					# 正式任务

					<最新>用户输入: %s
					范例数据: %s

					# 输出
					""", userQuery != null ? userQuery : "数据可视化", sqlResultJson);

			// 加载data-view-analyze提示词模板（系统提示词）
			String fullPrompt = PromptHelper.buildDataViewAnalysisPrompt();
			// 分割系统提示词和用户提示词模板
			String[] parts = fullPrompt.split("=== 用户输入 ===", 2);
			// 渲染系统提示词（当前没有变量，直接使用模板内容）
			String systemPrompt = parts[0].trim();

			log.debug("Built chart config generation system prompt as follows \n {} \n", systemPrompt);
			log.debug("Built chart config generation user prompt as follows \n {} \n", userPrompt);

			// 调用LLM生成图表配置（使用系统提示词和用户提示词）
			String chartConfigJson = llmService.toStringFlux(llmService.call(systemPrompt, userPrompt))
				.collect(StringBuilder::new, StringBuilder::append)
				.map(StringBuilder::toString)
				.block(Duration.ofMillis(properties.getEnrichSqlResultTimeout()));
			if (chartConfigJson != null && !chartConfigJson.trim().isEmpty()) {
				String content = MarkdownParserUtil.extractText(chartConfigJson.trim());
				displayStyle = jsonParseUtil.tryConvertToObject(content, DisplayStyleBO.class);
				log.debug("Successfully enriched ResultSetBO with chart config: type={}, title={}, x={}, y={}",
						displayStyle.getType(), displayStyle.getTitle(), displayStyle.getX(), displayStyle.getY());
				return displayStyle;
			}
			else {
				log.warn("LLM returned empty chart config, using default settings");
			}
		}
		catch (Exception e) {
			log.error("Failed to enrich ResultSetBO with chart config", e);
			// 不抛出异常，允许流程继续执行
		}
		return null;
	}

	private SqlRetryDto classifyQueryResult(OverAllState state, ResultSetBO resultSetBO) {
		if (resultSetBO == null || resultSetBO.getData() == null || resultSetBO.getData().isEmpty()) {
			if (isSpatialQuery(state)) {
				return SqlRetryDto.noTargetFound("未找到符合条件的空间目标对象，流程结束。");
			}
			return SqlRetryDto.emptyResult(EMPTY_RESULT_MESSAGE);
		}
		return SqlRetryDto.empty();
	}

	private SqlRetryDto classifyExecutionException(String errorMessage) {
		String normalized = errorMessage == null ? "" : errorMessage.toLowerCase();
		if (normalized.contains("unknown column") || normalized.contains("invalid column")
				|| normalized.contains("column") && normalized.contains("not found")
				|| normalized.contains("列名") && normalized.contains("无效")
				|| normalized.contains("对象名") && normalized.contains("无效")
				|| normalized.contains("must declare the scalar variable")
				|| normalized.contains("parameter") && normalized.contains("not supplied")
				|| normalized.contains("参数") && normalized.contains("未提供")
				|| normalized.contains("syntax")
				|| normalized.contains("grammar") || normalized.contains("near ")
				|| normalized.contains("function") && normalized.contains("not found")
				|| normalized.contains("invalid object name")) {
			return SqlRetryDto.retryableSql(errorMessage);
		}
		if (normalized.contains("permission") || normalized.contains("denied") || normalized.contains("login failed")
				|| normalized.contains("connection") || normalized.contains("timeout")
				|| normalized.contains("network")) {
			return SqlRetryDto.nonRetryableSql(errorMessage);
		}
		return SqlRetryDto.nonRetryableSql(errorMessage);
	}

	private boolean isSpatialQuery(OverAllState state) {
		String canonicalQuery = StateUtil.getCanonicalQuery(state);
		if (canonicalQuery == null) {
			return false;
		}
		String normalized = canonicalQuery.toLowerCase();
		return normalized.contains("空间") || normalized.contains("坐标") || normalized.contains("经度")
				|| normalized.contains("纬度") || normalized.contains("geometry") || normalized.contains("geography")
				|| normalized.contains("spatial") || normalized.contains("附近");
	}

}
